<?php
session_start();

// Initialize or retrieve chat session token
if (!isset($_SESSION['chat_session_id'])) {
    $_SESSION['chat_session_id'] = null; // FastAPI will generate and return one on first call
}

$userMessage = "What is the policy details?"; // Get this from your HTML form input
$apiUrl = "http://localhost:8001/chat";

$postData = [
    'session_id' => $_SESSION['chat_session_id'],
    'message' => $userMessage
];

$ch = curl_init($apiUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postData));
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json',
    'X-API-Key: dd_sk_114be8865b5f8f9ed22f590b61d6a9664ab039918c164b32'
]);

$response = curl_exec($ch);

if (!curl_errno($ch)) {
    $responseData = json_decode($response, true);
    
    // Save session ID generated by backend for subsequent turns
    $_SESSION['chat_session_id'] = $responseData['session_id'];
    
    // Display Bot Answer
    echo "Bot: " . htmlspecialchars($responseData['response']);
} else {
    echo "Error connecting to AI service.";
}

curl_close($ch);
?>
